export const MGS_ADD_TO_CART_SUCCESS = "Mua Hàng Thành Công !"
export const MGS_UPDATE_TO_CART_SUCCESS = "Cập Nhật Giỏ Hàng Thành Công !"
export const MGS_DELETE_IN_CART_SUCCESS = "Xóa Sản Phẩm Khỏi Giỏ Hàng Thành Công !"
export const MGS_CART_EMPTY = "Chưa Có Sản Phẩm Trong Giỏ Hàng!"
export const MGS_WELCOME = "Bạn Mua Hàng Vui Vẻ !"
